<?php

namespace AppBundle\Repository;

use AppBundle\Helper\PostFilter;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository {

    public function getListByFilter(PostFilter $filter) {
        $qb = $this->createQueryBuilder('post')
        ->select('post')
        ->setMaxResults($filter->getLimit())
        ->setFirstResult($filter->getOffset());
        if ($filter->getSearchQuery()) {
            $qb->andWhere('post.title LIKE :search OR post.description LIKE :search')
            ->setParameter('search', '%' . $filter->getSearchQuery() . '%');
        }
        $sort = $filter->getSort();
        if (is_array($sort) && sizeof($sort)) {
            foreach ($sort as $field => $value) {
                $qb->addOrderBy('post.' . $field, $value);
            }
        }

        return [
            'data' => $qb->getQuery()->getResult(),
            'total' => $this->getTotalByFilter($filter)
        ];
    }

    public function getTotalByFilter(PostFilter $filter) {
        $qb = $this->createQueryBuilder('post')
        ->select('COUNT(post.id)');
        if ($filter->getSearchQuery()) {
            $qb->andWhere('post.title LIKE :search OR post.description LIKE :search')
            ->setParameter('search', '%' . $filter->getSearchQuery() . '%');
        }
        return $qb->getQuery()->getSingleScalarResult();
    }

}
